-- require("nvim-tree").setup({
--     disable_netrw = true,
--     view = {
--         adaptive_size = true,
--         float = {
--             enable = true,
--         },
--     },
--     actions = {
--         open_file = {
--             quit_on_open = true,
--         }
--     },
--     on_attach = function(bufnr)
--         local api = require "nvim-tree.api"
--         local function opts(desc)
--             return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
--         end
--         -- default mappings
--         api.config.mappings.default_on_attach(bufnr)
--         -- custom mappings
--         vim.keymap.set('n', '<C-t>', api.tree.change_root_to_parent, opts('Up'))
--         vim.keymap.set('n', '<leader>pf', api.tree.close(), opts('Up'))
--         vim.keymap.set('n', '?', api.tree.toggle_help, opts('Help'))
--         vim.keymap.set('n', '<leader>nn', '<cmd>NvimTreeToggle<cr>', opts('Open file browser'))
--         vim.keymap.set('n', '<leader>nf', '<cmd>NvimTreeFindFile<cr>', opts('Find in file browser'))
--     end
-- })
